version: "3.7"

services:
  crossroad:
    build: .
    ports:
      - 8000:5000
    depends_on:
      - redis
    volumes:
      - type: bind
        source: ./app
        target: /app
  redis:
    image: "redis:alpine"
    ports:
    - 6379:6379
